version: 2.1
orbs:
  node: circleci/node@1.1.6


## WORKFLOW JOBS ##
jobs:

# DEPLOY JOB - Designate the desired docker image, install the AWS CLI, grab the cache set by the build job, deploy to s3 bucket #
  deploy:
    # working_directory: ~/dist
    docker:
      - image: circleci/node:12-browsers
        environment:
          # CHROME_BIN: "/usr/bin/google-chrome"
          NODE_ENV: "production"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Publish package
          command: npm publish




# BUILD JOB - Restores a cache if there is one, installs dependencies, build the application, set a new cache #
  build:
    executor:
      name: node/default
    docker:
      - image: circleci/node:12-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      # Log the current branch
      - run:
          name: Echo current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install product dependencies
          command: npm install
      # Build project with different configuration based on
      # the current branch
      - run:
          name: Building
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npm run build:prod
              else
                  npm run build
              fi

      # Cache the node_modules folder for the deploy job
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - node_modules
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
      - persist_to_workspace:
          root: .
          paths: .


## WORKFLOWS ##
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
          # filters:
          #   tags:
          #     only: /.*/
      - deploy:
          requires:
            - build
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/